# fly.toml app configuration file generated for cade-circular on 2023-07-05T14:24:09-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cade-circular"
primary_region = "gru"

[[mounts]]
  source = "data"
  destination = "/data"

[env]
  PORT = "3333"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
